### ISSUE TITLE
participation

### ISSUE THREAD

**Issue by jwijffels** [CLARIAH/IG-Text#5]
I personally would like to be kept up to date of this group (not sure what my contribution would be be just being kept up to date would be grea).  I'm basically interested in all kind of text related stuff, I'm mainly working on R alongside C++.
Open source code which I'm the author of are at https://github.com/bnosac/ and https://github.com/digi-vub/

**Comment by proycon** [comment]
Great! Welcome! Shall I also add you to our slack channel? (please send me a mail address in that case)

**Comment by jwijffels** [comment]
You can use the email at https://github.com/DIGI-VUB/image.textlinedetector/blob/34affeaa3f07f7782c0b635ad9fd1529f9e4fc09/DESCRIPTION#L5
